server:
  port: 8083
spring:
  application:
    name: notification-service
  datasource:
    url: ${ORACLE_URL:jdbc:oracle:thin:@//172.31.69.49:1521/FREEPDB1}
    username: ${ORACLE_USERNAME:SYSTEM}
    password: ${ORACLE_PASSWORD:12345678}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
app:
  rabbitmq:
    exchange: ${OT_NOTIFICATION_EXCHANGE:ot.notifications.exchange}
    queue: ${OT_NOTIFICATION_QUEUE:ot.notifications.queue}
    routing-key: ${OT_NOTIFICATION_ROUTING_KEY:ot.created}
