server:
  port: 8081

spring:
  application:
    name: ot-service
  datasource:
    url: ${ORACLE_URL:jdbc:oracle:thin:@//localhost:1521/FREEPDB1}
    username: ${ORACLE_USERNAME:TALLERPRO360}
    password: ${ORACLE_PASSWORD:12345678}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

app:
  kafka:
    ot-topic: ${OT_EVENT_TOPIC:ot.events}
  rabbitmq:
    exchange: ${OT_NOTIFICATION_EXCHANGE:ot.notifications.exchange}
    routing-key: ${OT_NOTIFICATION_ROUTING_KEY:ot.created}
