server:
  port: 8082
spring:
  application:
    name: event-service
  datasource:
    url: ${ORACLE_URL:jdbc:oracle:thin:@//localhost:1521/FREEPDB1}
    username: ${ORACLE_USERNAME:TALLERPRO360}
    password: ${ORACLE_PASSWORD:12345678}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_EVENT_GROUP:ot-event-service}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: cl.duoc.dsy1107.eventservice.dto.OtEventMessage
app:
  kafka:
    ot-topic: ${OT_EVENT_TOPIC:ot.events}
